### ISSUE TITLE
[Feature] Support Other Operating Systems?

### ISSUE THREAD

**Issue by Merith-TK** [codeonline-io/codeonline-community#10]
**Is your feature request related to a problem? Please describe.**
Yes/No? I personally use archlinux for my software development because i am guaranteed to use the latest libraries and programs for secure application development

Main examples
OpenSSH 8.2 released with USB 2FA support, (yubikey, fido), however both server and client in my experience, have to be at OpenSSH 8.2 for this to work at all. 

Ubuntu has 7.6 as its most recent available release, Most DEBIAN based Operating Systems are like this.

**Describe the solution you'd like**
Support for other Operating System bases, one example that i like, is ArchLinux. in which you can bundle a AUR package manager and use an AUR package which describes the files needed to download, the libraries needed to run, and what not. 
ArchLinux is pretty much EXTREMELY light compared to Ubuntu in overall usages,

I find ArchLinux is a great platform and practically MEANT to be used in this sort of situation.
I believe that Ubuntu and Debian based OS's are meant for the servers that need not die. Like the Back-end behind code-online. 
However Arch would be great as the container in which code-online users access.

Overall i feel as if archlinux would be a better, lighter alternative to Ubuntu in this setup that code-online has.

I am willing to be the tester should you choose to attempt to implement, i signed in with GitHub when creating my code-online account so it should be easy to find me on there 

feel free to ask questions as i am willing to share information on my setup if needbe

**Comment by Merith-TK** [comment]
SHIT, hit enter while going to the mouse to select the text box, SORRY, will edit

**Comment by steven166** [comment]
Thanks for you feedback.

We're currently using Ubuntu because of its general purpose. It is an operating system most developers are familiar with and it has a lot of tooling pre installed. 

Switching to a different distribution or adding more supported distributions to CodeOnline will either have breaking changes or have significant impact on the maintainability. Therefor I don't think we're going to support this on short notice. 

Maybe using Docker is a better solution for your use case. All CodeOnline workspaces come with a [pre installed Docker daemon](https://www.codeonline.io/docs/#/docker). You can use this to run your application in a Docker container, which can be based on any distribution you like. For example [ArchLinux](https://hub.docker.com/_/archlinux).

Let me know if this solution is suitable for your use case.

**Comment by Merith-TK** [comment]
And i understand why you chose to go with Ubuntu! it is a normal OS, 
Which is why i was thinking just arch for now as its system is not terribly different than Ubuntu when it comes to making sure programs can run!

im willing to help out if you guys want,

**Comment by steven166** [comment]
I understand that you would like this feature, but we cannot put this on our roadmap anytime soon. As there are other features that currently have a high priority. 

Have you tried the Docker solution? As that could solve your problem for now.

**Comment by Merith-TK** [comment]
I understand, i have not had a change yet to try out the docker solution but i do have a feeling that once i get it to a proper shell, it should work no problem

**Comment by Merith-TK** [comment]
i have not tried the docker solution yet, however i do know that once i learn how to actually do it, it will work just fine
